name: build
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: SDRReceiver
      # install MSYS2 for windows
      - name: if windows install MSYS2
        if: ${{ matrix.os == 'windows-latest' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain autoconf libtool mingw-w64-x86_64-cpputest mingw-w64-x86_64-qt5 mingw-w64-x86_64-cmake mingw-w64-x86_64-zeromq mingw-w64-x86_64-libusb zip p7zip unzip
      # build for windows
      - name: Windows-CI-Build
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo 'Running in MSYS2!'
          ./SDRReceiver/ci-windows-build.sh
        shell:  msys2 {0}
      # build for linux
      - name: Linux-CI-Build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo 'Running in bash!'
          chmod +x ./SDRReceiver/ci-linux-build.sh
          ./SDRReceiver/ci-linux-build.sh          
      # upload windows artifacts    
      - name: Upload windows binary artifacts
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: sdrrece_windows_windows
          retention-days: 1
          path: |
            SDRReceiver/SDRReceiver/release/*.zip
      # upload linux artifacts    
      - name: Upload linux binary artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: sdrreceiver_linux
          retention-days: 1
          path: |
            sdrreceiver/bin/*.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # download all artifacts for this workflow
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
      # Create a release
      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            sdrreceiver_linux/*.tar.gz
            sdrreceiver_windows/*.zip
